#! /usr/bin/env bash
##########################################################################
##									##
## Script ID: cnv2man							##
## Author: Mark Grant							##
##									##
## Purpose:								##
## To perform some string manipulation not possible in Makefile.am	##
## on parameters to be passed to txt2man.				##
##									##
## Syntax:	cnv2man TargetFileName SourceTextFileFullName \		##
##					TargetManualFullFileName	##
##									##
## Exit Codes:	0 & 64 - 113 as per C/C++ standard			##
##		0 - success						##
##		64 - Invalid arguments					##
##		67 - trap received					##
##									##
##########################################################################

##########################################################################
##									##
## Changelog								##
##									##
## Date		Author	Version	Description				##
##									##
## 17/06/2014	MG	1.0.1	Created.				##
##									##
##########################################################################

####################
## Init variables ##
####################
script_exit_code=0
outputprefix="cnv2man: "
version="1.0.1"				# set version variable

###############
## Functions ##
###############

# Output $1 to stdout or stderr depending on $2
output()
{
	if [ $2 = 0 ]
	then
		echo "$outputprefix$1"
	else
		echo "$outputprefix$1" 1>&2
	fi
}

# Standard function to tidy up and return exit code
script_exit()
{
	exit $script_exit_code
}

# Standard trap exit function
trap_exit()
{
script_exit_code=67
output "Script terminating due to trap received. Code: "$script_exit_code 1
script_exit
}

# Setup trap
trap trap_exit SIGHUP SIGINT SIGTERM

##########
## Main ##
##########

txt2man -t ${1%.*} -s 5 -v "Backup Scripts Manual" $2 > $3
txt2man_exit_code=$?

if [ $txt2man_exit_code = 0 ]
then
	output "Script completed successfully." 0
	script_exit_code=0
else
	output "txt2man failed with exit code: "$txt2man_exit_code 1
	script_exit_code=1
fi

script_exit


